// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.11
// source: user.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type OrderItemaddReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	OrderSn       string                 `protobuf:"bytes,2,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`
	OrderNum      int64                  `protobuf:"varint,3,opt,name=OrderNum,proto3" json:"OrderNum,omitempty"`
	OrderPrice    float32                `protobuf:"fixed32,4,opt,name=OrderPrice,proto3" json:"OrderPrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemaddReq) Reset() {
	*x = OrderItemaddReq{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemaddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemaddReq) ProtoMessage() {}

func (x *OrderItemaddReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemaddReq.ProtoReflect.Descriptor instead.
func (*OrderItemaddReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *OrderItemaddReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderItemaddReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *OrderItemaddReq) GetOrderNum() int64 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *OrderItemaddReq) GetOrderPrice() float32 {
	if x != nil {
		return x.OrderPrice
	}
	return 0
}

type OrderItemaddResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemaddResp) Reset() {
	*x = OrderItemaddResp{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemaddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemaddResp) ProtoMessage() {}

func (x *OrderItemaddResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemaddResp.ProtoReflect.Descriptor instead.
func (*OrderItemaddResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *OrderItemaddResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ShopaddReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Num           int64                  `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=Price,proto3" json:"Price,omitempty"`
	Count         int64                  `protobuf:"varint,4,opt,name=Count,proto3" json:"Count,omitempty"`
	Status        int64                  `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopaddReq) Reset() {
	*x = ShopaddReq{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopaddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopaddReq) ProtoMessage() {}

func (x *ShopaddReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopaddReq.ProtoReflect.Descriptor instead.
func (*ShopaddReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *ShopaddReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ShopaddReq) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *ShopaddReq) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ShopaddReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ShopaddReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ShopaddResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopaddResp) Reset() {
	*x = ShopaddResp{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopaddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopaddResp) ProtoMessage() {}

func (x *ShopaddResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopaddResp.ProtoReflect.Descriptor instead.
func (*ShopaddResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *ShopaddResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RecordaddReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductName   string                 `protobuf:"bytes,1,opt,name=ProductName,proto3" json:"ProductName,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	OrderSn       string                 `protobuf:"bytes,3,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`
	OrderNum      int64                  `protobuf:"varint,4,opt,name=OrderNum,proto3" json:"OrderNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordaddReq) Reset() {
	*x = RecordaddReq{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordaddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordaddReq) ProtoMessage() {}

func (x *RecordaddReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordaddReq.ProtoReflect.Descriptor instead.
func (*RecordaddReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *RecordaddReq) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *RecordaddReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RecordaddReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *RecordaddReq) GetOrderNum() int64 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

type RecordaddResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordaddResp) Reset() {
	*x = RecordaddResp{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordaddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordaddResp) ProtoMessage() {}

func (x *RecordaddResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordaddResp.ProtoReflect.Descriptor instead.
func (*RecordaddResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *RecordaddResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type OrderItemUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Status        int64                  `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemUpdateReq) Reset() {
	*x = OrderItemUpdateReq{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemUpdateReq) ProtoMessage() {}

func (x *OrderItemUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemUpdateReq.ProtoReflect.Descriptor instead.
func (*OrderItemUpdateReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *OrderItemUpdateReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderItemUpdateReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type OrderItemUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemUpdateResp) Reset() {
	*x = OrderItemUpdateResp{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemUpdateResp) ProtoMessage() {}

func (x *OrderItemUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemUpdateResp.ProtoReflect.Descriptor instead.
func (*OrderItemUpdateResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *OrderItemUpdateResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type OrderItemLikeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemLikeReq) Reset() {
	*x = OrderItemLikeReq{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemLikeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemLikeReq) ProtoMessage() {}

func (x *OrderItemLikeReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemLikeReq.ProtoReflect.Descriptor instead.
func (*OrderItemLikeReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *OrderItemLikeReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

type OrderItemLikeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	OrderSn       string                 `protobuf:"bytes,2,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`
	OrderNum      int64                  `protobuf:"varint,3,opt,name=OrderNum,proto3" json:"OrderNum,omitempty"`
	OrderPrice    float32                `protobuf:"fixed32,4,opt,name=OrderPrice,proto3" json:"OrderPrice,omitempty"`
	Status        int64                  `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemLikeResp) Reset() {
	*x = OrderItemLikeResp{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemLikeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemLikeResp) ProtoMessage() {}

func (x *OrderItemLikeResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemLikeResp.ProtoReflect.Descriptor instead.
func (*OrderItemLikeResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *OrderItemLikeResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderItemLikeResp) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *OrderItemLikeResp) GetOrderNum() int64 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *OrderItemLikeResp) GetOrderPrice() float32 {
	if x != nil {
		return x.OrderPrice
	}
	return 0
}

func (x *OrderItemLikeResp) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ShopListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopListReq) Reset() {
	*x = ShopListReq{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopListReq) ProtoMessage() {}

func (x *ShopListReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopListReq.ProtoReflect.Descriptor instead.
func (*ShopListReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *ShopListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ShopListReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ShopList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Num           int64                  `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=Price,proto3" json:"Price,omitempty"`
	Count         int64                  `protobuf:"varint,4,opt,name=Count,proto3" json:"Count,omitempty"`
	Status        int64                  `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopList) Reset() {
	*x = ShopList{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopList) ProtoMessage() {}

func (x *ShopList) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopList.ProtoReflect.Descriptor instead.
func (*ShopList) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *ShopList) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ShopList) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *ShopList) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ShopList) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ShopList) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ShopListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ShopList            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopListResp) Reset() {
	*x = ShopListResp{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopListResp) ProtoMessage() {}

func (x *ShopListResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopListResp.ProtoReflect.Descriptor instead.
func (*ShopListResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *ShopListResp) GetList() []*ShopList {
	if x != nil {
		return x.List
	}
	return nil
}

type OrderItemShowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemShowReq) Reset() {
	*x = OrderItemShowReq{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemShowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemShowReq) ProtoMessage() {}

func (x *OrderItemShowReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemShowReq.ProtoReflect.Descriptor instead.
func (*OrderItemShowReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *OrderItemShowReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type OrderItemShowResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	OrderSn       string                 `protobuf:"bytes,2,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`
	OrderNum      int64                  `protobuf:"varint,3,opt,name=OrderNum,proto3" json:"OrderNum,omitempty"`
	OrderPrice    float32                `protobuf:"fixed32,4,opt,name=OrderPrice,proto3" json:"OrderPrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemShowResp) Reset() {
	*x = OrderItemShowResp{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemShowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemShowResp) ProtoMessage() {}

func (x *OrderItemShowResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemShowResp.ProtoReflect.Descriptor instead.
func (*OrderItemShowResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *OrderItemShowResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderItemShowResp) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *OrderItemShowResp) GetOrderNum() int64 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *OrderItemShowResp) GetOrderPrice() float32 {
	if x != nil {
		return x.OrderPrice
	}
	return 0
}

type OrderItemListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemListReq) Reset() {
	*x = OrderItemListReq{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemListReq) ProtoMessage() {}

func (x *OrderItemListReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemListReq.ProtoReflect.Descriptor instead.
func (*OrderItemListReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *OrderItemListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *OrderItemListReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type OrderItemList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	OrderSn       string                 `protobuf:"bytes,2,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`
	OrderNum      int64                  `protobuf:"varint,3,opt,name=OrderNum,proto3" json:"OrderNum,omitempty"`
	OrderPrice    float32                `protobuf:"fixed32,4,opt,name=OrderPrice,proto3" json:"OrderPrice,omitempty"`
	Status        int64                  `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemList) Reset() {
	*x = OrderItemList{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemList) ProtoMessage() {}

func (x *OrderItemList) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemList.ProtoReflect.Descriptor instead.
func (*OrderItemList) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *OrderItemList) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderItemList) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *OrderItemList) GetOrderNum() int64 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *OrderItemList) GetOrderPrice() float32 {
	if x != nil {
		return x.OrderPrice
	}
	return 0
}

func (x *OrderItemList) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type OrderItemListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*OrderItemList       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemListResp) Reset() {
	*x = OrderItemListResp{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemListResp) ProtoMessage() {}

func (x *OrderItemListResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemListResp.ProtoReflect.Descriptor instead.
func (*OrderItemListResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *OrderItemListResp) GetList() []*OrderItemList {
	if x != nil {
		return x.List
	}
	return nil
}

type OrderItemdelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        int64                  `protobuf:"varint,1,opt,name=ShopId,proto3" json:"ShopId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemdelReq) Reset() {
	*x = OrderItemdelReq{}
	mi := &file_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemdelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemdelReq) ProtoMessage() {}

func (x *OrderItemdelReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemdelReq.ProtoReflect.Descriptor instead.
func (*OrderItemdelReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{20}
}

func (x *OrderItemdelReq) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *OrderItemdelReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type OrderItemdelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemdelResp) Reset() {
	*x = OrderItemdelResp{}
	mi := &file_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemdelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemdelResp) ProtoMessage() {}

func (x *OrderItemdelResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemdelResp.ProtoReflect.Descriptor instead.
func (*OrderItemdelResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{21}
}

func (x *OrderItemdelResp) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x05proto\"!\n" +
	"\vRegisterReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1e\n" +
	"\fRegisterResp\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\"\x7f\n" +
	"\x0fOrderItemaddReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x18\n" +
	"\aOrderSn\x18\x02 \x01(\tR\aOrderSn\x12\x1a\n" +
	"\bOrderNum\x18\x03 \x01(\x03R\bOrderNum\x12\x1e\n" +
	"\n" +
	"OrderPrice\x18\x04 \x01(\x02R\n" +
	"OrderPrice\"\"\n" +
	"\x10OrderItemaddResp\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\"x\n" +
	"\n" +
	"ShopaddReq\x12\x14\n" +
	"\x05Title\x18\x01 \x01(\tR\x05Title\x12\x10\n" +
	"\x03Num\x18\x02 \x01(\x03R\x03Num\x12\x14\n" +
	"\x05Price\x18\x03 \x01(\x02R\x05Price\x12\x14\n" +
	"\x05Count\x18\x04 \x01(\x03R\x05Count\x12\x16\n" +
	"\x06Status\x18\x05 \x01(\x03R\x06Status\"\x1d\n" +
	"\vShopaddResp\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\"~\n" +
	"\fRecordaddReq\x12 \n" +
	"\vProductName\x18\x01 \x01(\tR\vProductName\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\x12\x18\n" +
	"\aOrderSn\x18\x03 \x01(\tR\aOrderSn\x12\x1a\n" +
	"\bOrderNum\x18\x04 \x01(\x03R\bOrderNum\"\x1f\n" +
	"\rRecordaddResp\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\"<\n" +
	"\x12OrderItemUpdateReq\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x16\n" +
	"\x06Status\x18\x02 \x01(\x03R\x06Status\"%\n" +
	"\x13OrderItemUpdateResp\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\",\n" +
	"\x10OrderItemLikeReq\x12\x18\n" +
	"\aOrderSn\x18\x01 \x01(\tR\aOrderSn\"\x99\x01\n" +
	"\x11OrderItemLikeResp\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x18\n" +
	"\aOrderSn\x18\x02 \x01(\tR\aOrderSn\x12\x1a\n" +
	"\bOrderNum\x18\x03 \x01(\x03R\bOrderNum\x12\x1e\n" +
	"\n" +
	"OrderPrice\x18\x04 \x01(\x02R\n" +
	"OrderPrice\x12\x16\n" +
	"\x06Status\x18\x05 \x01(\x03R\x06Status\"5\n" +
	"\vShopListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"v\n" +
	"\bShopList\x12\x14\n" +
	"\x05Title\x18\x01 \x01(\tR\x05Title\x12\x10\n" +
	"\x03Num\x18\x02 \x01(\x03R\x03Num\x12\x14\n" +
	"\x05Price\x18\x03 \x01(\x02R\x05Price\x12\x14\n" +
	"\x05Count\x18\x04 \x01(\x03R\x05Count\x12\x16\n" +
	"\x06Status\x18\x05 \x01(\x03R\x06Status\"3\n" +
	"\fShopListResp\x12#\n" +
	"\x04list\x18\x01 \x03(\v2\x0f.proto.ShopListR\x04list\"\"\n" +
	"\x10OrderItemShowReq\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\"\x81\x01\n" +
	"\x11OrderItemShowResp\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x18\n" +
	"\aOrderSn\x18\x02 \x01(\tR\aOrderSn\x12\x1a\n" +
	"\bOrderNum\x18\x03 \x01(\x03R\bOrderNum\x12\x1e\n" +
	"\n" +
	"OrderPrice\x18\x04 \x01(\x02R\n" +
	"OrderPrice\":\n" +
	"\x10OrderItemListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"\x95\x01\n" +
	"\rOrderItemList\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x18\n" +
	"\aOrderSn\x18\x02 \x01(\tR\aOrderSn\x12\x1a\n" +
	"\bOrderNum\x18\x03 \x01(\x03R\bOrderNum\x12\x1e\n" +
	"\n" +
	"OrderPrice\x18\x04 \x01(\x02R\n" +
	"OrderPrice\x12\x16\n" +
	"\x06Status\x18\x05 \x01(\x03R\x06Status\"=\n" +
	"\x11OrderItemListResp\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.proto.OrderItemListR\x04list\"A\n" +
	"\x0fOrderItemdelReq\x12\x16\n" +
	"\x06ShopId\x18\x01 \x01(\x03R\x06ShopId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\",\n" +
	"\x10OrderItemdelResp\x12\x18\n" +
	"\aOrderSn\x18\x01 \x01(\tR\aOrderSn2\xf2\x04\n" +
	"\x04User\x123\n" +
	"\bRegister\x12\x12.proto.RegisterReq\x1a\x13.proto.RegisterResp\x12?\n" +
	"\fOrderItemadd\x12\x16.proto.OrderItemaddReq\x1a\x17.proto.OrderItemaddResp\x12H\n" +
	"\x0fOrderItemUpdate\x12\x19.proto.OrderItemUpdateReq\x1a\x1a.proto.OrderItemUpdateResp\x12B\n" +
	"\rOrderItemLike\x12\x17.proto.OrderItemLikeReq\x1a\x18.proto.OrderItemLikeResp\x120\n" +
	"\aShopadd\x12\x11.proto.ShopaddReq\x1a\x12.proto.ShopaddResp\x126\n" +
	"\tRecordadd\x12\x13.proto.RecordaddReq\x1a\x14.proto.RecordaddResp\x123\n" +
	"\bShopList\x12\x12.proto.ShopListReq\x1a\x13.proto.ShopListResp\x12B\n" +
	"\rOrderItemShow\x12\x17.proto.OrderItemShowReq\x1a\x18.proto.OrderItemShowResp\x12B\n" +
	"\rOrderItemList\x12\x17.proto.OrderItemListReq\x1a\x18.proto.OrderItemListResp\x12?\n" +
	"\fOrderItemdel\x12\x16.proto.OrderItemdelReq\x1a\x17.proto.OrderItemdelRespB\x03Z\x01/b\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_user_proto_goTypes = []any{
	(*RegisterReq)(nil),         // 0: proto.RegisterReq
	(*RegisterResp)(nil),        // 1: proto.RegisterResp
	(*OrderItemaddReq)(nil),     // 2: proto.OrderItemaddReq
	(*OrderItemaddResp)(nil),    // 3: proto.OrderItemaddResp
	(*ShopaddReq)(nil),          // 4: proto.ShopaddReq
	(*ShopaddResp)(nil),         // 5: proto.ShopaddResp
	(*RecordaddReq)(nil),        // 6: proto.RecordaddReq
	(*RecordaddResp)(nil),       // 7: proto.RecordaddResp
	(*OrderItemUpdateReq)(nil),  // 8: proto.OrderItemUpdateReq
	(*OrderItemUpdateResp)(nil), // 9: proto.OrderItemUpdateResp
	(*OrderItemLikeReq)(nil),    // 10: proto.OrderItemLikeReq
	(*OrderItemLikeResp)(nil),   // 11: proto.OrderItemLikeResp
	(*ShopListReq)(nil),         // 12: proto.ShopListReq
	(*ShopList)(nil),            // 13: proto.ShopList
	(*ShopListResp)(nil),        // 14: proto.ShopListResp
	(*OrderItemShowReq)(nil),    // 15: proto.OrderItemShowReq
	(*OrderItemShowResp)(nil),   // 16: proto.OrderItemShowResp
	(*OrderItemListReq)(nil),    // 17: proto.OrderItemListReq
	(*OrderItemList)(nil),       // 18: proto.OrderItemList
	(*OrderItemListResp)(nil),   // 19: proto.OrderItemListResp
	(*OrderItemdelReq)(nil),     // 20: proto.OrderItemdelReq
	(*OrderItemdelResp)(nil),    // 21: proto.OrderItemdelResp
}
var file_user_proto_depIdxs = []int32{
	13, // 0: proto.ShopListResp.list:type_name -> proto.ShopList
	18, // 1: proto.OrderItemListResp.list:type_name -> proto.OrderItemList
	0,  // 2: proto.User.Register:input_type -> proto.RegisterReq
	2,  // 3: proto.User.OrderItemadd:input_type -> proto.OrderItemaddReq
	8,  // 4: proto.User.OrderItemUpdate:input_type -> proto.OrderItemUpdateReq
	10, // 5: proto.User.OrderItemLike:input_type -> proto.OrderItemLikeReq
	4,  // 6: proto.User.Shopadd:input_type -> proto.ShopaddReq
	6,  // 7: proto.User.Recordadd:input_type -> proto.RecordaddReq
	12, // 8: proto.User.ShopList:input_type -> proto.ShopListReq
	15, // 9: proto.User.OrderItemShow:input_type -> proto.OrderItemShowReq
	17, // 10: proto.User.OrderItemList:input_type -> proto.OrderItemListReq
	20, // 11: proto.User.OrderItemdel:input_type -> proto.OrderItemdelReq
	1,  // 12: proto.User.Register:output_type -> proto.RegisterResp
	3,  // 13: proto.User.OrderItemadd:output_type -> proto.OrderItemaddResp
	9,  // 14: proto.User.OrderItemUpdate:output_type -> proto.OrderItemUpdateResp
	11, // 15: proto.User.OrderItemLike:output_type -> proto.OrderItemLikeResp
	5,  // 16: proto.User.Shopadd:output_type -> proto.ShopaddResp
	7,  // 17: proto.User.Recordadd:output_type -> proto.RecordaddResp
	14, // 18: proto.User.ShopList:output_type -> proto.ShopListResp
	16, // 19: proto.User.OrderItemShow:output_type -> proto.OrderItemShowResp
	19, // 20: proto.User.OrderItemList:output_type -> proto.OrderItemListResp
	21, // 21: proto.User.OrderItemdel:output_type -> proto.OrderItemdelResp
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
